language: php

php:
  - 5.3
  - 5.4
  - 5.5

script: phpunit --coverage-text --verbose .

before_script:
  - cd tests
  - pecl install apc
  - echo 'extension=apc.so' >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - bash ./travis-before_script.sh
